
-- Comando para adicionar a coluna de cor personalizada nos catálogos
ALTER TABLE catalogs 
ADD COLUMN IF NOT EXISTS primary_color TEXT DEFAULT '#4f46e5';

COMMENT ON COLUMN catalogs.primary_color IS 'Cor hexadecimal de identidade visual da vitrine pública';

-- GARANTIR QUE AS TABELAS USAM ID AUTO-INCREMENTO (IDENTITY) COM INT8
-- Isso evita o erro de "null value in column id violates not-null constraint"

-- Produtos
ALTER TABLE products 
ALTER COLUMN id SET DATA TYPE int8,
ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;

-- Adiciona coluna de histórico diretamente na tabela para simplicidade do app
ALTER TABLE products 
ADD COLUMN IF NOT EXISTS stock_history JSONB DEFAULT '[]'::jsonb;

-- Clientes
ALTER TABLE customers 
ALTER COLUMN id SET DATA TYPE int8,
ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;

-- Catálogos
ALTER TABLE catalogs 
ALTER COLUMN id SET DATA TYPE int8,
ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;

-- Orçamentos
ALTER TABLE quotations 
ALTER COLUMN id SET DATA TYPE int8,
ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;

-- Formas de Pagamento
ALTER TABLE payment_methods 
ALTER COLUMN id SET DATA TYPE int8,
ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;

-- SINCRONIZAÇÃO DE SEQUÊNCIAS (FIX PARA ERRO 23505 - DUPLICATE KEY)
SELECT setval(pg_get_serial_sequence('products', 'id'), coalesce(max(id), 0) + 1, false) FROM products;
SELECT setval(pg_get_serial_sequence('customers', 'id'), coalesce(max(id), 0) + 1, false) FROM customers;
SELECT setval(pg_get_serial_sequence('catalogs', 'id'), coalesce(max(id), 0) + 1, false) FROM catalogs;
SELECT setval(pg_get_serial_sequence('quotations', 'id'), coalesce(max(id), 0) + 1, false) FROM quotations;
SELECT setval(pg_get_serial_sequence('payment_methods', 'id'), coalesce(max(id), 0) + 1, false) FROM payment_methods;

-- TABELA DE HISTÓRICO DE ESTOQUE (OPCIONAL/AUDITORIA EXTERNA)
CREATE TABLE IF NOT EXISTS stock_history (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  product_id BIGINT REFERENCES products(id) ON DELETE CASCADE,
  user_id UUID REFERENCES users(id),
  previous_stock INTEGER NOT NULL,
  new_stock INTEGER NOT NULL,
  change_amount INTEGER NOT NULL,
  reason TEXT NOT NULL, -- 'manual_adjustment', 'sale_delivery', 'return'
  reference_id TEXT, -- ID do orçamento ou código do ajuste
  notes TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Índices para performance
CREATE INDEX IF NOT EXISTS idx_stock_history_product ON stock_history(product_id);
CREATE INDEX IF NOT EXISTS idx_stock_history_user ON stock_history(user_id);

-- Habilitar RLS (Row Level Security)
ALTER TABLE stock_history ENABLE ROW LEVEL SECURITY;

-- Políticas de acesso para stock_history
CREATE POLICY "Users can insert their own stock history" 
ON stock_history FOR INSERT 
TO authenticated 
WITH CHECK (true);

CREATE POLICY "Users can view their own stock history" 
ON stock_history FOR SELECT 
TO authenticated 
USING (true);

-- ADICIONAR COLUNA DE FORMA DE PAGAMENTO EM QUOTATIONS
ALTER TABLE quotations 
ADD COLUMN IF NOT EXISTS payment_method_id int8 REFERENCES payment_methods(id) ON DELETE SET NULL;

COMMENT ON COLUMN quotations.payment_method_id IS 'ID da forma de pagamento associada ao orçamento (int8)';
